#!/bin/sh

if [ -f 'hquery/history.db' ]
then
    rm hquery/history.db
fi

cat 'historic_events/historic_events.tsv' \
 | python pipeline/jsonify.py \
 | python pipeline/store.py

mv history.db hquery/history.db
