#!/bin/sh

if [ -f 'chronicle/history.db' ]
then
    rm chronicle/history.db
fi

cat 'historic_events/historic_events.tsv' \
 | python pipeline/jsonify.py \
 | python pipeline/store.py

mv history.db chronicle/history.db
